<?php
/**
 * ProjectMetaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BitbucketClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * bitbucket Rest Resources
 *
 * This is the bitbucket rest resources endpoint documentation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BitbucketClient;

use PHPUnit\Framework\TestCase;

/**
 * ProjectMetaTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectMeta
 * @package     BitbucketClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProjectMetaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectMeta"
     */
    public function testProjectMeta()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "public"
     */
    public function testPropertyPublic()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
