<?php
/**
 * BitbucketApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BitbucketClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * bitbucket Rest Resources
 *
 * This is the bitbucket rest resources endpoint documentation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BitbucketClient;

use \BitbucketClient\Configuration;
use \BitbucketClient\ApiException;
use \BitbucketClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BitbucketApiTest Class Doc Comment
 *
 * @category Class
 * @package  BitbucketClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BitbucketApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getProject
     *
     * Returns information about a project..
     *
     */
    public function testGetProject()
    {
    }
}
